version: '2'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
